// src/components/hero/Theme.tsx
import { DarkIcon } from "../icons/theme/DarkIcon";
import { LightIcon } from "../icons/theme/LightIcon";

import { useState } from "react";

export function Theme() {
  const [theme, setTheme] = useState(() => {
    const getTheme = localStorage.getItem("color-theme") ?? "dark";
    document.documentElement.classList.add(getTheme);
    return getTheme;
  });

  function toggleTheme() {
    if (theme === "dark") {
      document.documentElement.classList.remove("dark");
      localStorage.setItem("color-theme", "light");
      setTheme("light");
    } else {
      document.documentElement.classList.add("dark");
      localStorage.setItem("color-theme", "dark");
      setTheme("dark");
    }
  }

  return (
    <button
      className={`btn flex justify-center items-center rounded-full hover:shadow-inner h-11 w-11 dark:bg-primary-700 bg-secondary-500`}
      onClick={toggleTheme}
    >
      {theme === "light" ? <LightIcon /> : <DarkIcon />}
    </button>
  );
}

// src/components/hero/Theme.svelte
<script>
  import { onMount } from "svelte";

  import LightIcon from "../icons/theme/LightIcon.svelte";
  import DarkIcon from "../icons/theme/DarkIcon.svelte";

  let theme = "dark";

  onMount(() => {
    theme = localStorage.getItem("color-theme") ?? "dark";
    document.documentElement.classList.add("dark");
  });

  function toggleTheme() {
    if (theme === "dark") {
      document.documentElement.classList.remove("dark");
      localStorage.setItem("color-theme", "light");
      theme = "light";
    } else {
      document.documentElement.classList.add("dark");
      localStorage.setItem("color-theme", "dark");
      theme = "dark";
    }
  }
</script>

<button
  class="btn flex justify-center items-center rounded-full"
  on:click={toggleTheme}
>
  {#if theme === "light"}
    <LightIcon />
  {:else}
    <DarkIcon />
  {/if}
</button>

<style>
  button {
    @apply h-11 w-11 bg-primary-600;

    &:hover {
      box-shadow: 0px 0px 8px 4px #1d222f inset;
      transform: scale(0.95);
      @apply bg-primary-500;
    }
  }
</style>
